config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  devise_for :users
  resources :users, only: %i[index show]
  resources :meditations do 
    resources :comments
  end
  resources :collections
  resources :subscriptions, only: [:create, :destroy, :index]

  resources :users do
    member do
      delete :delete_image_attachment
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :meditations, only: [:show]
    end
  end

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 1, maximum: 255 }
  has_many :meditations
  has_many :subscriptions
  has_many :users, through: :subscriptions
end
 

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :meditation

  validates :content, presence: {
    message: "Dodaj treść komentarza.."
  }
end

app/models/meditation.rb
class Meditation < ApplicationRecord
  has_one_attached :meditationFile
  belongs_to :collection
  has_many :comments

  validates :name,
            presence: true,
            uniqueness: true
  validates :collection_id, presence: true
  validates :meditationFile, presence: {
    message: "Dodaj plik z medytacją.."
  }
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :collection
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :comments
  has_many :subscriptions
  has_many :collections, through: :subscriptions
  validates :nick,
            presence: true,
            uniqueness: true
  validate :avatar_extension

  def resize
    return self.avatar.variant(resize: '300x300')
  end

  private

  def avatar_extension
   return unless avatar.attached? && !avatar.content_type.in?(%w[image/jpeg image/png])

   errors.add(:avatar, 'must be a JPG or a PNG file.')
  end


end

app/controllers/api/v1/meditations_controller.rb
class Api::V1::MeditationsController < ApplicationController 
  def show 
    @meditation = Meditation.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :nick, :avatar, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :nick, :avatar, :email, :password, :current_password) }
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_collection, only: %i[show destroy edit update]
  def new 
    @collection = Collection.new
  end

  def show 
    @meditations = @collection.meditations
  end

  def create
    @collection = Collection.new(collection_params)
    if @collection.save 
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit; end

  def update 
    if @collection.update(collection_params) 
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @collection.destroy
    redirect_to users_path
  end

  private

  def collection_params 
    params.require(:collection).permit(:name, :description)
  end

  def find_collection
    @collection = Collection.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_meditation, only: %i[create edit update destroy]
  before_action :find_comment, only: %i[edit update destroy]
  def create
    @comment = @meditation.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to meditation_path(@meditation)
      flash[:notice] = 'Komentarz dodany..'
    else
      redirect_to meditation_path(@meditation)
      flash[:notice] = 'Komentarz nie został dodany..'
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to meditation_path(@meditation)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to meditation_path(@meditation)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_meditation
    @meditation = Meditation.find(params[:meditation_id])
  end

  def find_comment
    @comment = @meditation.comments.find(params[:id])
  end
end

app/controllers/meditations_controller.rb
class MeditationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_meditation, only: %i[show destroy edit update]
  before_action :meditation_params, only: %i[create update]
  before_action :set_collections, only: %i[new create edit update]

  def index
    @meditations = Meditation.all
  end

  def new
    @meditation = Meditation.new
  end

  def create
    @meditation = Meditation.new(meditation_params)
    @meditation.collection_id = params[:collection_id]
    if @meditation.save
      flash[:notice] = 'Medytacja została dodana.'
      redirect_to meditations_path
    else 
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    @meditation.collection_id = params[:collection_id]
    if @meditation.update(meditation_params)
      flash[:notice] = 'Medytacja została edytowana.'
      redirect_to meditations_path
    else
      render 'edit'
    end
  end

  def destroy
    @meditation.destroy
    redirect_to meditations_path
  end

  private

  def meditation_params
    params.require(:meditation).permit(:name, :meditationFile, :collection_id)
  end

  def find_meditation
    @meditation = Meditation.find(params[:id])
  end

  def set_collections
    @collections = Collection.all.map { |c| [c.name, c.id] }
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def index 
    @subscriptions = Subscription.all
    @userCollections = current_user.collections
   
  end

  def create 
    @subscription = Subscription.create(user_id: current_user.id, collection_id: params[:collection_id])
    @subscription.save
    redirect_to users_path
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
    flash[:notice] = "Subskrycja anulowana"
    redirect_to users_path
  end

  private 

  def find_subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_params, only: %i[show delete_image_attachment]
  def index
  @collections = Collection.all

  @subscription = Subscription.find_by(user_id: current_user)
  end
  def show
    @user = User.find(params[:id])
  end

  def delete_image_attachment
    @avatar = ActiveStorage::Attachment.find(params[:id])
    @avatar.purge
    redirect_back(fallback_location: request.referer)
  end

  private

  def user_params 
    params.permit(:email, :id, :avatar, :nick)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/collections/_form.html.erb
<%= form_for @collection do |f| %>
  <div class="form-group">
    <% if @collection.errors.any? %>
  <ul>
    <% @collection.errors.each do |attr,msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
    <%= f.text_field :name, placeholder: "Wprowadź nazwę kolekcji..", autofocus: true %>
    <%= f.text_area :description, placeholder: "Dodaj opis tej kolekcjii", autofocus: true %>
    <%= f.submit(@collection.new_record? ? "Dodaj post" : "Edytuj post") %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h2>Edytuj kolekcję</h2>
<%= render 'form' %>

app/views/collections/new.html.erb
<h2>Dodaj nową kolekcję</h2>
<%= render 'form' %>

app/views/collections/show.html.erb
<%= @collection.name %> <br>
<%= @collection.description %>
<% @meditations.each do |meditation| %>
  <h2><%= meditation.name %></h2>
  <% if current_user.admin === true %>
   <%= link_to "Usuń", meditation_path(meditation), method: :delete, data: {confirm: 'Czy jesteś pewien?'}, class: "link" %> 
    <%= link_to "Edytuj", edit_meditation_path(meditation), class: 'link' %>
  <% end %>
    <%= link_to "Osłuchaj", meditation_path(meditation), class: 'link' %>
<% end %>

app/views/comments/_comment.html.erb
<div>
  <p><%= comment.content %></p>
  <p>By: <%= comment.user.nick %></p>
  <div class="links">
  <% if user_signed_in? %>
    <% if comment.user_id == current_user.id %>
    <%= link_to "Edytuj", edit_meditation_comment_path(comment.meditation, comment) %>
    <%= link_to "Delete", meditation_comment_path(comment.meditation, comment), method: :delete, data: {confirm: "Czy jesteś pewien?"} %>
    <% end %>
  <% end %>  
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@meditation, @meditation.comments.build] do |f| %>
  <%= f.text_area :content %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edycja komentarza</h1>
<%= form_for [@meditation, @comment] do |f| %>
  <%= f.text_area :content %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MediApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  
  </head>

  <body>
    <div class ="main-page">
      <%= render 'users/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      
    </div>
  </body>
</html>

app/views/meditations/_form.html.erb
<div class="form-new">
  <%= form_for @meditation do |f| %>
  <% if @meditation.errors.any? %>
  <ul>
    <% @meditation.errors.each do |attr,msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
    <div class="form-group">
      <%= link_to "Dodaj nową kolekcje", new_collection_path, class: 'link' %><br>

      <%= f.text_field :name, placeholder: "Wprowadź nazwę medytacjii..", autofocus: true %><br>
          <%= select_tag(:collection_id, options_for_select(@collections), {:prompt => "Wybierz kolekcję"}) %><br>
      <%= f.label "Plik audio" %>
      <%= f.file_field :meditationFile %><br>
      <%= f.submit(@meditation.new_record? ? "Dodaj medytacje" : "Edytuj post") %>
    </div>
    <%= link_to "Wróć", meditations_path, class: 'link' %>
  <% end %>
</div>

app/views/meditations/edit.html.erb
<%= form_for @meditation, html: {multiple: true} do |f| %>
<% if @meditation.errors.any? %>
<ul>
  <% @meditation.errors.each do |attr,msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
  <div class="form-group">
    <%= link_to "Dodaj nową kolekcje", new_collection_path, class: 'link' %><br>
    <%= f.select :collection_id, @collections %>
    <%= f.text_field :name, placeholder: "Wprowadź nazwę medytacjii..", autofocus: true %><br>
    <%= f.label "Plik audio" %>
    <%= f.file_field :meditationFile %><br>
    <%= f.submit(@meditation.new_record? ? "Dodaj medytacje" : "Edytuj post") %>
  </div>
  <%= link_to "Wróć", meditations_path, class: 'link' %>
<% end %>

app/views/meditations/index.html.erb
  <%= link_to "Dodaj nową medytację", new_meditation_path, class: 'link' %>
    <h3>Lista dodanych medytacji</h3>
  <% @meditations.each do |meditation| %>
    <br>
    <br>
    <h4><%= meditation.name %></h4>
    <%= link_to "Usuń", meditation_path(meditation), method: :delete, data: {confirm: 'Czy jesteś pewien?'}, class: "link" %> 
    <%= link_to "Edytuj", edit_meditation_path(meditation), class: 'link' %>
    <%= link_to "Osłuchaj", meditation_path(meditation), class: 'link' %>
  <% end %>

app/views/meditations/new.html.erb
<div class="meditation-container">
  <h1>Nowa medytacja:</h1>
  <%= render 'form' %>
</div>

app/views/meditations/show.html.erb
<div id="play-page"></div>
  <%= javascript_pack_tag 'components/play-page' %>
<h3>comments</h3>
  <p>
    <%= render @meditation.comments %>
  </p>
<h3>Dodaj komentarz</h3>
<%= render 'comments/form' %>

app/views/subscriptions/index.html.erb
<% @userCollections.each do |collection| %>

 <h3><%= collection.name %></h3>
        <p><%= collection.description %></p>
        <div class="collection-box-content-links">
        <%= link_to "Zobacz kolekcje", collection_path(collection), class: "link" %>


<% end %>

app/views/users/_navbar.html.erb
<div id="navbar">
  <% if current_user %>
  <%= javascript_pack_tag 'navbar' %>
  <% end %>
</div>

app/views/users/index.html.erb
<% if current_user%>
   <%= link_to "Twoje Subskrypcje", subscriptions_path, class: "link" %>
<% @collections.each do |collection| %>
  <% if current_user.admin === true %>
    <h1>Admin Panel</h1>
  
      <button><%= link_to "Dodaj Medytacje", new_meditation_path, class: 'link'%></button>
      <button><%= link_to "Dodaj Kolekcję", new_collection_path, class: 'link'%></button>
      <div class="collection-box">
      


      <div class="collection-box-content">
        <h3><%= collection.name %></h3>
        <p><%= collection.description %></p>
        <div class="collection-box-content-links">
        <%= link_to "Zobacz kolekcje", collection_path(collection), class: "link" %>
        <%= link_to "Edytuj kolekcje", edit_collection_path(collection), class: "link" %>
        <%= link_to "Usuń", collection_path(collection), method: :delete, data: {confirm: 'Czy jesteś pewien?'}, class: "link" %> 
        </div>
      </div>
      
      </div>
    <% else %>
        
        <div class="collection-box">
      
      <div class="collection-box-content">
        <h3><%= collection.name %></h3>
        <p><%= collection.description %></p>
        <div class="collection-box-content-links">
        <%= link_to "Zobacz kolekcje", collection_path(collection), class: "link" %>


        <%if @current_user.collections.include?(collection)%>
        <%= link_to "Unsub", subscription_path(@subscription), method: :delete, data: {confirm: "are you sure?"} %>
        <% else %>
        <%= link_to "Sub", subscriptions_path(user_id: current_user.id, collection_id: collection.id), class: "link", method: :post %>
        <% end %>        
     
          
      
        </div>
      </div>
      
      </div>
  <% end %>
  <% end %>
<% else %>
  <p>Możesz zalogować się ponownie <br> <%= link_to "zaloguj", new_user_session_path %> </p>
<% end %>
  

app/views/users/show.html.erb
<%= @user.email %>
<%= @user.nick %>
<%= @user.id %>